name: Test Build Pipeline CICD

on:
  workflow_call:
    inputs:
      REACT_APP_API_AUTH_URL_PFV:
        description: "URL de l'API Auth PFV"
        required: true
        type: string
      REACT_APP_API_AUTH_URL_PRD:
        description: "URL de l'API Auth PRD"
        required: true
        type: string
      REACT_APP_API_COMPONENT_URL_PFV:
        description: "URL de l'API Component PFV"
        required: true
        type: string
      REACT_APP_API_COMPONENT_URL_PRD:
        description: "URL de l'API Component PRD"
        required: true
        type: string
      REACT_APP_URL:
        description: "URL de l'application"
        required: true
        type: string
      REACT_APP_THEME:
        description: "Thème de l'application"
        required: true
        type: string
      REACT_APP_ENV:
        description: "Environnement de l'application"
        required: true
        type: string
      REACT_APP_FRONT_AUTHENTIFICATION_PFV:
        description: "URL de l'authentification front PFV"
        required: true
        type: string
      REACT_APP_FRONT_AUTHENTIFICATION_PRD:
        description: "URL de l'authentification front PRD"
        required: true
        type: string
    secrets:
      TOKEN_GITHUB:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      KUBECONFIG_PRD:
        required: true
      KUBECONFIG_PFV:
        required: true
      GCP_SA_KEY_PRD:
        required: true
      GCP_SA_KEY_PFV:
        required: true

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: token github
      run: git config --global url."https://${{ secrets.TOKEN_GITHUB }}@github.com/".insteadOf "ssh://git@github.com/"

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    # Test du Dockerfile pour vérifier la construction de l'image
    - name: Build Docker image
      run: |
        docker build -t my-app:latest .
      # Vérifier si Docker est installé
      env:
        DOCKER_BUILDKIT: 1  # Utilise BuildKit pour des builds plus rapides et plus efficaces
