# .github/workflows/theme-pipeline.yml
name: Theme Pipeline

on:
  workflow_call:  # Ce workflow est conçu pour être réutilisé
    inputs: {}

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Okk
        run: echo "okk"
